sonar.organization=mutrapro-kcpm
sonar.projectKey=Mutrapro-KCPM_mutrapro_system_testing

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/logs/**,**/uploads/**,**/output/**,**/*.jar,**/package-lock.json
