sonar.organization=mutrapro-kcpm
sonar.projectKey=Mutrapro-KCPM_mutrapro_system_testing

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,**/logs/**,**/uploads/**,**/output/**,**/*.jar,**/package-lock.json,postman/**,Reports md/**,docs/**,ci/**,tests/**,.github/**

sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=postman/**,Reports md/**