const request = require('supertest');
const app = require('../../index');

describe('A.6: Đánh giá dịch vụ (POST /:id/feedback)', () => {
    beforeEach(() => { jest.clearAllMocks(); });

    it('[Real Payload] [EP] ORD-FB-05 - Lỗi rating chữ cái', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": "abc",
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": "abc",
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [EP] ORD-FB-06 - Lỗi rating số thập phân', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 4.5,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": 4.5,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [EP] ORD-FB-08 - Lỗi comment quá dài', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 3,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": 3,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [EP] ORD-FB-09 - Lỗi feedback đơn chưa thanh toán', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 3,
    "comment": "Đơn này chưa thanh toán nên sẽ lỗi"
}`); } catch(e) { payload = `{
    "rating": 3,
    "comment": "Đơn này chưa thanh toán nên sẽ lỗi"
}`; }
        const res = await request(app)
            .post('/{{temp_pending_order_id}}/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [EP] ORD-FB-10 - Lỗi gửi feedback lần 2 (trùng lặp)', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 4,
    "comment": "Đánh giá lần 2 sẽ bị 409"
}`); } catch(e) { payload = `{
    "rating": 4,
    "comment": "Đánh giá lần 2 sẽ bị 409"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [BVA] ORD-FB-01 - Feedback hợp lệ tại biên min', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 1,
    "comment": ""
}`); } catch(e) { payload = `{
    "rating": 1,
    "comment": ""
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(200);
    });
    it('[Real Payload] [BVA] ORD-FB-02 - Feedback hợp lệ tại biên max', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 5,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": 5,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(200);
    });
    it('[Real Payload] [BVA] ORD-FB-03 - Lỗi rating dưới min', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 0,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": 0,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [BVA] ORD-FB-04 - Lỗi rating vượt max', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 6,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": 6,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
    it('[Real Payload] [BVA] ORD-FB-07 - Lỗi comment vượt mức max', async () => {
        global.mockPool.execute.mockResolvedValueOnce([[{ id: 9, status: 'completed', customer_id: 1 }]]).mockResolvedValueOnce([[]]).mockResolvedValueOnce([[{ affectedRows: 1 }]]);
        let payload = null;
        try { payload = JSON.parse(`{
    "rating": 5,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`); } catch(e) { payload = `{
    "rating": 5,
    "comment": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}`; }
        const res = await request(app)
            .post('/9/feedback')
            .send(payload);
        
        expect(res.status).toBe(400);
    });
});